Use Arctis USB Finder NPM Package
atagulalan/arctis-battery-percentage pull request #20
Opened 2021-01-29 17:56 UTC by richrace

:wave: So this uses the package I've built which is based on your work to load/find the Arctis USB devices.

I split it out into it's own package as I plan on making an Electron tray version (https://github.com/richrace/arctis-monitor).

The [Arctis USB Finder](https://github.com/richrace/arctis-usb-finder) package also includes support for the Arctis 7X (with some additional fields). 

Let me know what you think. 

Happy for this to be rejected/accepted 😀

2021-01-30 09:04 UTC, atagulalan commented on percentage.js
> +const getHeadphoens = require('arctis-usb-finder').default
nit: typo

2021-01-30 09:08 UTC, atagulalan requested changes
Excellent work! There is a small typo, but overall, this is great.

I am currently looking for a maintainer. If you are interested, please reply this comment.

Thank you.

2021-01-30 09:40 UTC, atagulalan approved these changes

2021-01-30 09:41 UTC, merged

2021-02-01 09:06 UTC, richrace commented on percentage.js
> +const getHeadphoens = require('arctis-usb-finder').default
🙈  Thanks for fixing this.

2021-02-01 09:07 UTC, richrace commented
Thanks for merging 🎉  

I'd happily be a maintainer to bump this dependency when I update it in the future. I just don't have access to a Windows PC (or a VM) at the moment so I won't be extending the functionality or manually testing this.